# Generated by Django 3.1.2 on 2020-11-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_size', models.CharField(max_length=255, verbose_name='Название размера')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subcategories', models.CharField(max_length=255, verbose_name='Подкатегория')),
                ('slug', models.SlugField(unique=True)),
                ('name_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mens_business_clothing.categories', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(upload_to='')),
                ('image_4', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание товара')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mens_business_clothing.categories', verbose_name='Категория')),
                ('size', models.ManyToManyField(to='Mens_business_clothing.Size', verbose_name='Размер')),
                ('subcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mens_business_clothing.subcategories', verbose_name='Подкатегория')),
                ('сolor', models.ManyToManyField(to='Mens_business_clothing.Color', verbose_name='Цвета товара')),
            ],
        ),
    ]
