# Generated by Django 3.1.2 on 2020-11-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mens_business_clothing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Название 0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(upload_to='', verbose_name='Название 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(upload_to='', verbose_name='Название 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(upload_to='', verbose_name='Название 3'),
        ),
    ]
