# Generated by Django 3.1.2 on 2020-11-26 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mens_business_clothing', '0003_auto_20201113_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol', models.BigIntegerField(max_length=3, verbose_name='Кол-во товара')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Basket_description', to='Mens_business_clothing.product', verbose_name='Описание')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Basket_image', to='Mens_business_clothing.product', verbose_name='Картинка')),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Basket_name_product', to='Mens_business_clothing.product', verbose_name='Название продукта')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Basket_price', to='Mens_business_clothing.product', verbose_name='Цена')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Basket_size', to='Mens_business_clothing.product', verbose_name='Размер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Корзина')),
                ('сolor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Basket_color', to='Mens_business_clothing.product', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
