# Generated by Django 3.1.2 on 2020-11-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mens_business_clothing', '0005_auto_20201130_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='image',
        ),
    ]
