# Generated by Django 3.1.2 on 2020-12-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mens_business_clothing', '0008_auto_20201225_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.TextField(default=1, max_length=3000, verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
